version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 794038243494.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Pulling the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest 794038243494.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
  build:
    commands:
      - echo Pushing the Docker image...
      - docker push 794038243494.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
