version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking Docker version...
      - docker --version
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 794038243494.dkr.ecr.us-east-1.amazonaws.com || exit 1
      - echo ECR login successful
      - REPOSITORY_URI=794038243494.dkr.ecr.us-east-1.amazonaws.com/flask-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app . || exit 1
      - echo Docker build successful
      - docker tag flask-app:latest $REPOSITORY_URI:latest || exit 1
      - echo Docker tag successful
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest || exit 1
      - echo Docker push successful

artifacts:
  files:
    - '**/*'