version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Checking Python and pip versions
      - python --version
      - pip --version
      - echo Installing Flask
      - pip install flask
      - echo Checking Docker version
      - docker --version
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 794038243494.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=794038243494.dkr.ecr.us-east-1.amazonaws.com/flask-app
  build:
    commands:
      - echo Build started on `date`
      - echo Contents of the current directory
      - ls -la
      - echo Contents of the Dockerfile
      - cat Dockerfile
      - echo Building the Docker image
      - docker build --no-cache -t flask-app .
      - echo Docker build successful
      - docker tag flask-app:latest $REPOSITORY_URI:latest
      - echo Docker tag successful
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push $REPOSITORY_URI:latest
      - echo Docker push successful

artifacts:
  files:
    - '**/*'